---
version: "3.6"

services:

  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${DOCKER_CONF_DIR}/nginx-proxy/certs:/etc/nginx/certs
      - ${DOCKER_CONF_DIR}/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ${DOCKER_CONF_DIR}/nginx-proxy/html:/usr/share/nginx/html
      - ${DOCKER_CONF_DIR}/nginx-proxy/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443

  nginx-proxy-acme:
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${USER_EMAIL}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_CONF_DIR}/nginx-proxy/certs:/etc/nginx/certs
      - ${DOCKER_CONF_DIR}/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ${DOCKER_CONF_DIR}/nginx-proxy/html:/usr/share/nginx/html
      - ${DOCKER_CONF_DIR}/nginx-proxy-acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy

  ddclient:
    container_name: ddclient
    image: ghcr.io/linuxserver/ddclient
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_CONF_DIR}/ddclient:/config

  portainer:
    hostname: ${DOCKERHOSTNAME}
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - VIRTUAL_HOST=portainer.${USER_SUBDOMAIN}
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.${USER_SUBDOMAIN}
      - LETSENCRYPT_EMAIL=${USER_EMAIL}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_CONF_DIR}/portainer:/data
    ports:
      - 127.0.0.1:9000:9000

  mariadb:
    container_name: mariadb
    image: ghcr.io/linuxserver/mariadb
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${ROOT_ACCESS_PASSWORD}
      - MYSQL_DATABASE=${USER_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${DOCKER_CONF_DIR}/mariadb:/config
    ports:
      - 127.0.0.1:3306:3306

  gitea:
    container_name: gitea
    image: gitea/gitea
    restart: unless-stopped
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mariadb:3306
      - GITEA__database__NAME=${USER_DB_NAME}
      - GITEA__database__USER=${MYSQL_USER}
      - GITEA__database__PASSWD=${DATABASE_PASSWORD}
      - VIRTUAL_HOST=gitea.${USER_DOMAIN}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=gitea.${USER_DOMAIN}
      - LETSENCRYPT_EMAIL=${USER_EMAIL}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_CONF_DIR}/gitea:/data
     ports:
       - 127.0.0.1:3000:3000
       - 222:22
     depends_on:
       - mariadb
